#!/usr/bin/env node

/**
 * Debug script to test Claude Code file permissions specifically
 */

import { query } from "@anthropic-ai/claude-code";
import { config } from 'dotenv';
import { join } from 'path';

config({ path: join(__dirname, '.env.local') });

async function debugPermissions() {
  console.log('🔍 Debugging Claude Code File Permissions');
  console.log('==========================================\n');

  const simplePrompt = `
TASK: Create a simple HTML file named "test.html" with the following content:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test File</title>
</head>
<body>
    <h1>Hello from Claude Code!</h1>
    <p>This file was generated by Claude Code SDK.</p>
</body>
</html>

CRITICAL INSTRUCTIONS:
1. You MUST use the Write tool to create the file "test.html"
2. Do NOT just show the code - ACTUALLY CREATE THE FILE
3. Confirm the file creation in your response
4. You have explicit permission to write files

Write the file NOW.
`;

  console.log('📝 Simple file creation test...\n');

  try {
    const messages = [];
    
    for await (const message of query({
      prompt: simplePrompt,
      abortController: new AbortController(),
      options: {
        maxTurns: 2,
        cwd: process.cwd(),
      },
    })) {
      messages.push(message);
      console.log(`📨 Message type: ${message.type}`);
      
      // Log message content for debugging
      if (message.type === 'assistant' || message.type === 'result') {
        console.log('📝 Message content:', JSON.stringify(message, null, 2));
      }
    }

    console.log(`\n📊 Total messages: ${messages.length}`);
    
    // Check if file was created
    const fs = require('fs');
    const filePath = join(process.cwd(), 'test.html');
    
    if (fs.existsSync(filePath)) {
      console.log('🎉 SUCCESS: test.html was created!');
      const content = fs.readFileSync(filePath, 'utf8');
      console.log('📄 File content:');
      console.log(content);
    } else {
      console.log('❌ FAILURE: test.html was NOT created');
      console.log('This indicates a permissions or configuration issue.');
    }

  } catch (error) {
    console.error('💥 Error:', error);
  }
}

if (require.main === module) {
  debugPermissions().catch(console.error);
}